services:
    hammer663.BoardRules.listener:
        class: hammer663\BoardRules\event\listener
        arguments:
            - @auth
            - @config
            - @user
            - @dbal.conn
            - @template				
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
    hammer663.BoardRules.controller:
        class: hammer663\BoardRules\controller\rules
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
